name: Deploy

on:
    push:
        branches:
            - master
        pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build

            - name: CNAME
              if: ${{ github.event_name == 'push' }}
              run: |
                  cd ./src/.vitepress/dist/
                  touch CNAME
                  echo "routup.net" > CNAME

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./src/.vitepress/dist
